service: expenses-service 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  expenses:
    handler: expenses.handler
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
      DB_NAME: ${opt:DB_NAME}
    events:
      - http:
          path: expenses
          method: get
          cors: true
      - http:
          path: expenses
          method: post
          cors: true
      - http:
          path: expenses/{id}
          method: delete
          cors: true
      - http:
          path: expenses/{id}
          method: put
          cors: true