service: expenses-service 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  expenses:
    handler: expenses.handler
    events:
      - http:
          path: expenses
          method: get
          cors: true
      - http:
          path: expenses
          method: post
          cors: true
      - http:
          path: expenses/{id}
          method: delete
          cors: true
      - http:
          path: expenses/{id}
          method: put
          cors: true